# Generated by Django 3.2.25 on 2025-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0010_remove_course_max_numb_students_course_max_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_numb_students',
            field=models.IntegerField(default=30),
        ),
    ]
