# Generated by Django 3.2.25 on 2025-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0012_alter_course_max_numb_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('06:45 - 08:20', '6:45 AM - 8:20 AM'), ('08:20 - 10:00', '8:20 AM - 10:00 AM'), ('10:00 - 10:50', '10:00 AM - 10:50 AM'), ('10:50 - 12:30', '10:50 AM - 12:30 PM'), ('12:30 - 14:10', '12:30 PM - 2:10 PM')], default='11:30 - 12:30', max_length=50),
        ),
    ]
