# Generated by Django 3.2.25 on 2025-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0013_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('6:45 am - 8:20 am', '6:45 am - 8:20 am'), ('8:20 am - 10:00 am', '8:20 am - 10:00 am'), ('10:00 am - 10:50 am', '10:00 am - 10:50 am'), ('10:50 am - 12:30 pm', '10:50 am - 12:30 pm'), ('12:30 pm - 2:10 PM', '12:30 pm - 2:10 pm')], default='11:30 - 12:30', max_length=50),
        ),
    ]
