# Generated by Django 3.2.25 on 2025-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0014_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('6:45 AM - 8:20 AM', '6:45 AM - 8:20 AM'), ('8:20 AM - 10:00 AM', '8:20 AM - 10:00 AM'), ('10:00 AM - 10:50 AM', '10:00 AM - 10:50 AM'), ('10:50 AM - 12:30 PM', '10:50 AM - 12:30 PM'), ('12:30 PM - 2:10 PM', '12:30 PM - 2:10 PM')], default='11:30 - 12:30', max_length=50),
        ),
    ]
