# Generated by Django 3.2.25 on 2025-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0017_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('6:45 - 8:20', '6:45 - 8:20'), ('8:20 - 10:00', '8:20 - 10:00'), ('10:00 - 10:50', '10:00 - 10:50'), ('10:50 - 12:30', '10:50 - 12:30'), ('12:30 - 2:10', '12:30 - 2:10')], default='11:30 - 12:30', max_length=50),
        ),
    ]
