# Generated by Django 3.2.25 on 2025-02-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0018_alter_meetingtime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
    ]
