# Generated by Django 3.2.25 on 2025-02-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0019_remove_section_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room'),
        ),
    ]
