# Generated by Django 3.2.25 on 2025-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0021_remove_course_max_numb_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_numb_students',
            field=models.IntegerField(default=48),
        ),
    ]
